#! /bin/bash

export DEPLOYTOOLS_MOUNTS="{{ mounts }}"
export DEPLOYTOOLS_APPTAINER_ARGS="{{ apptainer_args }}"
export DEPLOYTOOLS_SIF_NAME="{{ sif_name }}"
export DEPLOYTOOLS_SIF_VERSION="{{ sif_version }}"
export DEPLOYTOOLS_COMMAND="{{ command }}"
export DEPLOYTOOLS_COMMAND_ARGS="{{ command_args }}"

$(dirname "$0")/apptainer-launch "${@}"