#! /bin/bash

# Arguments:
# ${@} = Remaining args to pass to the command

# Halt on error
set -e

# Mounts for container
mounts="/dls/science/users/:/dls/science/users/,/scratch:/scratch,/dls_sw/apps:/dls_sw/apps"
# Additional arguments for apptainer
apptainer_args=""
# Sif file path
sif_file="$(dirname $0)/../sif_files/00558f3680613da6ad6091d87ea4d3ff.sif"
# Command to run in container
command="ec"
# Options and arguments to pass to command
command_args=""

# Raise an error if sif file does not exist
if [[ ! -f ${sif_file} ]]; then
    echo "ERROR: sif file ${sif_file} does not exist" 1>&2
    exit 1
fi

# add mounts of host binaries into /usr/bin
for i in argocd kubectl helm kubelogin klogout kustomize kubeseal kubectl-oidc_login; do
    binary=$(which $i)
    mounts="${mounts},${binary}:/usr/bin/${i}"
done

# Set up mounts if any have been configured
if [[ ! -z ${mounts} ]]; then
    opts="-B ${mounts}"
fi

opts=${opts}" --env DISPLAY=${DISPLAY}"
opts=${opts}" ${apptainer_args}"


if [[ -n "${DEPLOY_TOOLS_VERBOSE}" ]]; then
    set -x
fi
apptainer exec ${opts} ${sif_file} ${command} ${command_args} "${@}"
