# yaml-language-server: $schema=/workspaces/deploy-tools/src/deploy_tools/models/schemas/release.json

module:
  name: p47
  version: dev
  description: ec command line tool for kubernetes IOCs

  env_vars:
    - name: EC_TARGET
      value: p47-beamline/p47
    - name: EC_SERVICES_REPO
      value: https://github.com/epics-containers/p47-services

  dependencies:
    - name: pollux
      version: "local"
    - name: edge-containers-cli
      version: "0.1"

  applications: []
