# yaml-language-server: $schema=../../models/schemas/module-metadata.json

name: example-module-folder
version: "0.1"
description: Demonstration of a module configuration folder

env_vars:
  - name: OTHER_VALUE
    value: CAN_SEE_THIS
