# yaml-language-server: $schema=/workspaces/deploy-tools/src/deploy_tools/models/schemas/release.json

module:
  name: ec-p47
  version: dev
  description: Command line setup for p47 beamline

  dependencies:
    - name: edge-containers-cli
      version: "0.1"
    - name: pollux
      version: local

  applications:
    - app_type: shell
      name: ec
      script:
        - ec-apptainer --target p47-beamline/p47 --repo https://github.com/epics-containers/p47-services ${@}
